name: Test

on:
  push:
    branches: "*"
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Install dependencies
      run: python -m pip install -U jupyterlab==4.0.2

    - name: Install the extension
      run: |
        set -eux
        jlpm
        python -m pip install .

    - name: UI Test Setup
      run: jlpm install
      working-directory: ui-tests

    - name: "UI Test Setup: Install Chromium"
      run: jlpm playwright install chromium
      working-directory: ui-tests

    - name: Run UI Test
      run: jlpm playwright test
      working-directory: ui-tests
